# Generated by Django 5.2.4 on 2025-07-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrocomercial',
            options={'verbose_name_plural': 'Centros Comerciales'},
        ),
        migrations.AlterModelOptions(
            name='tienda',
            options={'verbose_name_plural': 'Locales'},
        ),
        migrations.AddField(
            model_name='centrocomercial',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
