# Generated by Django 5.2.4 on 2025-07-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_centrocomercial_options_alter_tienda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrocomercial',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
